// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace AgenciaDeViagem.DATA.Models
{
    public partial class AgenciadeviagemContext : DbContext
    {
        public AgenciadeviagemContext()
        {
        }

        public AgenciadeviagemContext(DbContextOptions<AgenciadeviagemContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Agencia> Agencia { get; set; }
        public virtual DbSet<Compra> Compra { get; set; }
        public virtual DbSet<Passagens> Passagens { get; set; }
        public virtual DbSet<Pessoas> Pessoas { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=DESKTOP-IER3FDV\\MSSQLSERVER2019;Initial Catalog=agenciaDeViagem;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Latin1_General_CI_AS");

            modelBuilder.Entity<Agencia>(entity =>
            {
                entity.HasKey(e => e.CódAgencia)
                    .HasName("PK__AGENCIA__AC13330B4A3D2EFF");

                entity.Property(e => e.MenuServiços).IsUnicode(false);
            });

            modelBuilder.Entity<Compra>(entity =>
            {
                entity.HasKey(e => e.CódCompra)
                    .HasName("PK__COMPRA__8C4E82F810FB9CCA");

                entity.Property(e => e.DadosCompra).IsUnicode(false);

                entity.HasOne(d => d.CódAgenciaNavigation)
                    .WithMany(p => p.Compra)
                    .HasForeignKey(d => d.CódAgencia)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_CódAgencia_Agencia");

                entity.HasOne(d => d.CódPassagemNavigation)
                    .WithMany(p => p.Compra)
                    .HasForeignKey(d => d.CódPassagem)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_CódPassagem_Passagem");

                entity.HasOne(d => d.CódPessoaNavigation)
                    .WithMany(p => p.Compra)
                    .HasForeignKey(d => d.CódPessoa)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_CódPessoa_Pessoa");
            });

            modelBuilder.Entity<Passagens>(entity =>
            {
                entity.HasKey(e => e.CódPassagem)
                    .HasName("PK__PASSAGEN__B98D7BEBF3B5F7DF");

                entity.Property(e => e.Destino).IsUnicode(false);

                entity.Property(e => e.Trecho).IsUnicode(false);
            });

            modelBuilder.Entity<Pessoas>(entity =>
            {
                entity.HasKey(e => e.CódPessoa)
                    .HasName("PK__PESSOAS__1BE7B15B067F9B71");

                entity.Property(e => e.Cpf).IsUnicode(false);

                entity.Property(e => e.Nome).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}