// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace AgenciaDeViagem.DATA.Models
{
    [Table("AGENCIA")]
    public partial class Agencia
    {
        public Agencia()
        {
            Compra = new HashSet<Compra>();
        }

        [Key]
        public int CódAgencia { get; set; }
        [Required]
        [StringLength(50)]
        public string MenuServiços { get; set; }

        [InverseProperty("CódAgenciaNavigation")]
        public virtual ICollection<Compra> Compra { get; set; }
    }
}