// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace AgenciaDeViagem.DATA.Models
{
    [Table("COMPRA")]
    public partial class Compra
    {
        [Key]
        public int CódCompra { get; set; }
        public int CódPessoa { get; set; }
        public int CódPassagem { get; set; }
        public int CódAgencia { get; set; }
        [Required]
        [StringLength(300)]
        public string DadosCompra { get; set; }

        [ForeignKey(nameof(CódAgencia))]
        [InverseProperty(nameof(Agencia.Compra))]
        public virtual Agencia CódAgenciaNavigation { get; set; }
        [ForeignKey(nameof(CódPassagem))]
        [InverseProperty(nameof(Passagens.Compra))]
        public virtual Passagens CódPassagemNavigation { get; set; }
        [ForeignKey(nameof(CódPessoa))]
        [InverseProperty(nameof(Pessoas.Compra))]
        public virtual Pessoas CódPessoaNavigation { get; set; }
    }
}