// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace AgenciaDeViagem.DATA.Models
{
    [Table("PESSOAS")]
    public partial class Pessoas
    {
        public Pessoas()
        {
            Compra = new HashSet<Compra>();
        }

        [Key]
        public int CódPessoa { get; set; }
        [Required]
        [StringLength(150)]
        public string Nome { get; set; }
        [Required]
        [Column("CPF")]
        [StringLength(11)]

        [DisplayName("CPF")]
        public string Cpf { get; set; }

        [DisplayName("Quantidade de Pessoas")]
        public int QtdPessoas { get; set; }
        
        [InverseProperty("CódPessoaNavigation")]
        public virtual ICollection<Compra> Compra { get; set; }
    }
}